"""Pluggable vector index for the vector-store service.

=====================================================================
WHY THIS FILE EXISTS
=====================================================================
This service answers one question: "given a new vector, what's the closest
vector you've already seen?" WHICH engine performs that nearest-neighbour search
is a replaceable detail -- the spec lists FAISS, Chroma, or an in-memory index
as interchangeable options.

This module defines that seam as a small REGISTRY:

  - VectorIndex       the abstract contract every index engine must satisfy
  - register(name)    a decorator that adds an index factory to the registry
  - FaissVectorIndex  the demo adapter (FAISS IndexIDMap), self-registered
  - create_from_env() builds the index named by VECTOR_INDEX_BACKEND

To add your own engine you DO NOT edit this file. Drop a module into
app/plugins/ that subclasses VectorIndex and calls @register("your-name"); it is
auto-imported at startup. Then set VECTOR_INDEX_BACKEND=your-name.

The index deals ONLY in numbers and ids. It never sees a sentence or a reply;
those live in Redis/the persistence store, a separate service. The distance
convention (lower == more similar) is owned by the injected SimilarityMetric.
"""

from __future__ import annotations

import os
import uuid
from abc import ABC, abstractmethod
from typing import Callable

import faiss
import numpy as np

from ._plugins import load_plugins
from .metrics import SimilarityMetric

# Built-in backend names selectable via the VECTOR_INDEX_BACKEND env var.
BACKEND_FAISS = "faiss"

DEFAULT_BACKEND = BACKEND_FAISS


class SearchResult:
    """Outcome of a nearest-vector search.

    hit == False means no stored vector was within threshold; id/distance are
    unset in that case.
    """

    def __init__(self, hit: bool, entry_id: str = "", distance: float = -1.0) -> None:
        self.hit = hit
        self.entry_id = entry_id
        self.distance = distance


class VectorIndex(ABC):
    """Contract for a store of vectors that supports nearest-neighbour search."""

    @property
    @abstractmethod
    def dim(self) -> int:
        """Required length of every vector this index accepts."""

    @abstractmethod
    def search(self, vector: list[float], top_k: int, threshold: float) -> SearchResult:
        """Return the nearest stored vector within threshold, else a miss."""

    @abstractmethod
    def upsert(self, vector: list[float]) -> str:
        """Store a vector and return its generated public id."""

    @abstractmethod
    def delete(self, entry_id: str) -> bool:
        """Remove a vector by id. Returns False if the id was unknown."""

    @abstractmethod
    def rebuild(self, entries: list[tuple[str, list[float]]]) -> int:
        """Replace all contents with (id, vector) pairs. Returns the count."""

    @abstractmethod
    def size(self) -> int:
        """Number of vectors currently stored."""

    @abstractmethod
    def flush(self) -> None:
        """Drop all stored vectors."""


# --- registry -------------------------------------------------------------
# An index factory takes (dim, metric) -- injected by main.py so the index
# engine and the similarity metric can be swapped independently -- and returns a
# ready VectorIndex.
VectorIndexFactory = Callable[[int, SimilarityMetric], VectorIndex]

_REGISTRY: dict[str, VectorIndexFactory] = {}


def register(name: str) -> Callable[[VectorIndexFactory], VectorIndexFactory]:
    """Register a vector-index factory under name (use as a decorator)."""

    def decorator(factory: VectorIndexFactory) -> VectorIndexFactory:
        _REGISTRY[name] = factory
        return factory

    return decorator


class FaissVectorIndex(VectorIndex):
    """FAISS adapter.

    Uses a flat (exact/brute-force) index whose distance type is chosen by the
    injected metric, wrapped in IndexIDMap so each vector keeps its own integer
    id even as neighbours are deleted. FAISS only speaks integer ids, so we keep
    a two-way phrasebook between public UUID strings and those integers.
    """

    def __init__(self, dim: int, metric: SimilarityMetric) -> None:
        self._dim = dim
        self._metric = metric
        self._reset()

    def _reset(self) -> None:
        # Rebuild the whole index from scratch -- simpler and safer than
        # clearing FAISS's internal state piece by piece. faiss.IndexFlat takes
        # the metric type directly, so the same code serves cosine and L2.
        self._base_index = faiss.IndexFlat(self._dim, self._metric.faiss_metric_type)
        self._index = faiss.IndexIDMap(self._base_index)
        self._uuid_to_int: dict[str, int] = {}
        self._int_to_uuid: dict[int, str] = {}
        self._next_int_id = 0

    @property
    def dim(self) -> int:
        return self._dim

    def _to_np(self, vec: list[float]) -> np.ndarray:
        # FAISS insists on a 2D float32 numpy array, even for a single vector.
        return np.array([vec], dtype="float32")

    def _require_dim(self, vector: list[float], context: str = "") -> None:
        if len(vector) != self._dim:
            raise ValueError(
                f"vector{context} has dimension {len(vector)}, want {self._dim}"
            )

    def search(self, vector: list[float], top_k: int, threshold: float) -> SearchResult:
        if self._index.ntotal == 0:
            return SearchResult(hit=False)
        self._require_dim(vector)

        scores, ids = self._index.search(self._to_np(vector), min(top_k, self._index.ntotal))
        best_score = scores[0][0]
        best_int_id = ids[0][0]

        # FAISS's own "found nothing" sentinel is id == -1.
        if best_int_id == -1:
            return SearchResult(hit=False)

        distance = self._metric.to_distance(best_score)
        if distance <= threshold:
            return SearchResult(hit=True, entry_id=self._int_to_uuid[best_int_id], distance=distance)
        # Found something, but not close enough to count.
        return SearchResult(hit=False)

    def upsert(self, vector: list[float]) -> str:
        self._require_dim(vector)
        entry_id = uuid.uuid4().hex  # public id the orchestrator will use
        int_id = self._next_int_id   # private id FAISS uses internally
        self._next_int_id += 1

        self._uuid_to_int[entry_id] = int_id
        self._int_to_uuid[int_id] = entry_id
        self._index.add_with_ids(self._to_np(vector), np.array([int_id], dtype="int64"))
        return entry_id

    def delete(self, entry_id: str) -> bool:
        if entry_id not in self._uuid_to_int:
            return False
        int_id = self._uuid_to_int.pop(entry_id)
        self._int_to_uuid.pop(int_id)
        # remove_ids works because we're using IndexIDMap; a plain flat index
        # can only clear everything.
        self._index.remove_ids(np.array([int_id], dtype="int64"))
        return True

    def rebuild(self, entries: list[tuple[str, list[float]]]) -> int:
        self._reset()
        if not entries:
            return 0

        vectors: list[np.ndarray] = []
        int_ids: list[int] = []
        for entry_id, vector in entries:
            self._require_dim(vector, f" for entry {entry_id!r}")
            if entry_id in self._uuid_to_int:
                raise ValueError(f"duplicate entry id {entry_id!r}")
            int_id = self._next_int_id
            self._next_int_id += 1
            self._uuid_to_int[entry_id] = int_id
            self._int_to_uuid[int_id] = entry_id
            vectors.append(np.array(vector, dtype="float32"))
            int_ids.append(int_id)

        self._index.add_with_ids(np.array(vectors, dtype="float32"), np.array(int_ids, dtype="int64"))
        return len(entries)

    def size(self) -> int:
        return int(self._index.ntotal)

    def flush(self) -> None:
        self._reset()


@register(BACKEND_FAISS)
def _build_faiss(dim: int, metric: SimilarityMetric) -> VectorIndex:
    return FaissVectorIndex(dim, metric)


def create_from_env(dim: int, metric: SimilarityMetric) -> VectorIndex:
    """Build the vector index selected by VECTOR_INDEX_BACKEND (default faiss).

    dim and metric are injected by the caller (main.py). Loads any drop-in
    plugins first, then looks the backend up. Unknown backends raise, so a typo
    fails fast at startup.
    """
    load_plugins()
    name = os.getenv("VECTOR_INDEX_BACKEND", DEFAULT_BACKEND)
    if name not in _REGISTRY:
        raise ValueError(
            f"unknown vector store backend {name!r} (registered: {sorted(_REGISTRY)})"
        )
    return _REGISTRY[name](dim, metric)
