"""Pluggable similarity metrics for the vector-store service.

=====================================================================
WHY THIS FILE EXISTS
=====================================================================
"How similar are two vectors?" has more than one valid answer -- cosine
similarity and Euclidean distance are the two classic ones, and the spec lists
"support for multiple similarity metrics" as a planned feature. The metric is
therefore a pluggable seam, defined here as a small REGISTRY.

A metric owns two coupled decisions:

  1. faiss_metric_type -- which FAISS distance FAISS should compute internally
     (inner product for cosine on unit vectors, L2 for Euclidean).
  2. to_distance()     -- how to turn FAISS's raw score into OUR public
     convention: a "distance" where LOWER means MORE similar and a hit requires
     distance <= threshold.

To add your own metric you DO NOT edit this file. Drop a module into
app/plugins/ that subclasses SimilarityMetric and calls @register("your-name");
it is auto-imported at startup. Then set SIMILARITY_METRIC=your-name.
"""

from __future__ import annotations

import os
from abc import ABC, abstractmethod
from typing import Callable

import faiss

from ._plugins import load_plugins

# Built-in metric names selectable via the SIMILARITY_METRIC env var.
METRIC_COSINE = "cosine"
METRIC_EUCLIDEAN = "euclidean"

DEFAULT_METRIC = METRIC_COSINE


class SimilarityMetric(ABC):
    """Contract every similarity metric must satisfy."""

    @property
    @abstractmethod
    def name(self) -> str:
        """Human-readable identifier of the metric."""

    @property
    @abstractmethod
    def faiss_metric_type(self) -> int:
        """The faiss.METRIC_* constant FAISS should compute for this metric."""

    @abstractmethod
    def to_distance(self, faiss_score: float) -> float:
        """Convert FAISS's raw score into our distance convention.

        Lower distance == more similar, so a hit is distance <= threshold.
        """


# --- registry -------------------------------------------------------------
# A metric factory takes no arguments and returns a ready SimilarityMetric.
MetricFactory = Callable[[], SimilarityMetric]

_REGISTRY: dict[str, MetricFactory] = {}


def register(name: str) -> Callable[[MetricFactory], MetricFactory]:
    """Register a similarity-metric factory under name (use as a decorator)."""

    def decorator(factory: MetricFactory) -> MetricFactory:
        _REGISTRY[name] = factory
        return factory

    return decorator


class CosineMetric(SimilarityMetric):
    """Cosine distance = 1 - cosine similarity, over unit-length vectors.

    Because the embedder normalizes vectors to length 1, FAISS's inner product
    IS the cosine similarity, so distance = 1 - similarity. Range [0, 2], with
    0.0 meaning identical direction.
    """

    name = METRIC_COSINE
    faiss_metric_type = faiss.METRIC_INNER_PRODUCT

    def to_distance(self, faiss_score: float) -> float:
        return 1.0 - float(faiss_score)


class EuclideanMetric(SimilarityMetric):
    """Straight-line (L2) distance between vectors.

    FAISS's METRIC_L2 returns the SQUARED distance, so we take the square root
    to report the true Euclidean distance. Lower is already more similar, so no
    inversion is needed.
    """

    name = METRIC_EUCLIDEAN
    faiss_metric_type = faiss.METRIC_L2

    def to_distance(self, faiss_score: float) -> float:
        return float(faiss_score) ** 0.5


@register(METRIC_COSINE)
def _build_cosine() -> SimilarityMetric:
    return CosineMetric()


@register(METRIC_EUCLIDEAN)
def _build_euclidean() -> SimilarityMetric:
    return EuclideanMetric()


def create_from_env() -> SimilarityMetric:
    """Build the similarity metric selected by SIMILARITY_METRIC (default cosine).

    Loads any drop-in plugins first, then looks the metric up. Unknown names
    raise, so a typo fails fast at startup.
    """
    load_plugins()
    name = os.getenv("SIMILARITY_METRIC", DEFAULT_METRIC)
    if name not in _REGISTRY:
        raise ValueError(
            f"unknown similarity metric {name!r} (registered: {sorted(_REGISTRY)})"
        )
    return _REGISTRY[name]()
