"""Pluggable embedding models for the embedding service.

=====================================================================
WHY THIS FILE EXISTS
=====================================================================
The embedding service does exactly one job: turn a sentence into a list of
numbers that represents its MEANING. *Which* model produces those numbers is a
replaceable detail -- the spec calls the embedding model "interchangeable
(pluggable)".

This module defines that seam as a small REGISTRY:

  - EmbeddingModel        the abstract contract every model must satisfy
  - register(name)        a decorator that adds a model factory to the registry
  - SentenceTransformerModel  the demo adapter (all-MiniLM-L6-v2), self-registered
  - create_from_env()     builds the model named by EMBEDDING_MODEL_BACKEND

To add your own model you DO NOT edit this file. Drop a module into
app/plugins/ that subclasses EmbeddingModel and calls @register("your-name");
it is auto-imported at startup (see _plugins.py). Then set
EMBEDDING_MODEL_BACKEND=your-name.

Note on normalization: adapters return UNIT-LENGTH vectors (length == 1). That
is what lets the vector store treat inner product as cosine similarity. An
adapter that cannot normalize should document the similarity metric it expects.
"""

from __future__ import annotations

import os
from abc import ABC, abstractmethod
from typing import Callable

from ._plugins import load_plugins

# Built-in backend names selectable via the EMBEDDING_MODEL_BACKEND env var.
BACKEND_SENTENCE_TRANSFORMERS = "sentence-transformers"

DEFAULT_BACKEND = BACKEND_SENTENCE_TRANSFORMERS
DEFAULT_MODEL_NAME = "all-MiniLM-L6-v2"


class EmbeddingModel(ABC):
    """Contract for anything that turns text into an embedding vector.

    Implementations expose their own ``name`` and ``dim`` so callers never have
    to hardcode a dimension -- it is a property of whichever model is loaded.
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Human-readable identifier of the underlying model."""

    @property
    @abstractmethod
    def dim(self) -> int:
        """Number of components in every vector this model produces."""

    @abstractmethod
    def embed(self, text: str) -> list[float]:
        """Convert a text prompt into a unit-length embedding vector."""


# --- registry -------------------------------------------------------------
# A factory takes no arguments and returns a ready EmbeddingModel. It reads any
# settings it needs (model name, API keys) from the environment itself, so a
# new backend never requires changing this module.
EmbeddingModelFactory = Callable[[], EmbeddingModel]

_REGISTRY: dict[str, EmbeddingModelFactory] = {}


def register(name: str) -> Callable[[EmbeddingModelFactory], EmbeddingModelFactory]:
    """Register an embedding-model factory under name (use as a decorator)."""

    def decorator(factory: EmbeddingModelFactory) -> EmbeddingModelFactory:
        _REGISTRY[name] = factory
        return factory

    return decorator


class SentenceTransformerModel(EmbeddingModel):
    """Demo adapter backed by a sentence-transformers model.

    The model weights are loaded once (in __init__, at startup) and reused for
    every request, because loading is slow but inference is fast.
    """

    def __init__(self, model_name: str = DEFAULT_MODEL_NAME) -> None:
        # Imported lazily so alternative backends do not pay the heavy
        # sentence-transformers import cost unless this adapter is actually used.
        from sentence_transformers import SentenceTransformer

        self._name = model_name
        self._model = SentenceTransformer(model_name)
        # DIM is read FROM the model rather than hardcoded, so swapping to a
        # model with a different output size just works.
        self._dim = int(self._model.get_sentence_embedding_dimension())

    @property
    def name(self) -> str:
        return self._name

    @property
    def dim(self) -> int:
        return self._dim

    def embed(self, text: str) -> list[float]:
        # normalize_embeddings=True scales the output to unit length, which is
        # what makes inner product == cosine similarity downstream in the
        # vector store. Without it the store's cosine distance math is wrong.
        vec = self._model.encode(text, normalize_embeddings=True)
        return vec.tolist()


@register(BACKEND_SENTENCE_TRANSFORMERS)
def _build_sentence_transformer() -> EmbeddingModel:
    return SentenceTransformerModel(os.getenv("EMBEDDING_MODEL", DEFAULT_MODEL_NAME))


def create_from_env() -> EmbeddingModel:
    """Build the embedding model selected by EMBEDDING_MODEL_BACKEND.

    Loads any drop-in plugins first so their @register runs, then looks the
    backend up. Unknown backends raise, so a typo fails fast at startup.
    """
    load_plugins()
    name = os.getenv("EMBEDDING_MODEL_BACKEND", DEFAULT_BACKEND)
    if name not in _REGISTRY:
        raise ValueError(
            f"unknown embedding backend {name!r} (registered: {sorted(_REGISTRY)})"
        )
    return _REGISTRY[name]()
